services:
  jewellery-catalogue-minio:
    image: "minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1"
    container_name: jewellery-catalogue-minio 
    ports:
      - "7000:9000"
      - "7001:9001"
    command: [ "server", "--console-address", ":9001", "/data/minio" ]
    env_file:
    - .env
    volumes:
      - jewellery-catalogue-minio-data:/data/minio

  jewellery-catalogue-mongodb:
    image: mongodb/mongodb-community-server
    container_name: jewellery-catalogue-mongodb
    ports:
      - '27017:27017'
    volumes:
      - jewellery-catalogue-mongo-data:/data/db

  jewellery-catalogue-api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    env_file:
      - .env
    container_name: jewellery-catalogue-api
    ports:
      - '3001:3001'
    depends_on:
      - jewellery-catalogue-mongodb
      - jewellery-catalogue-minio

  jewellery-catalogue-web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
      args:
         VITE_API_URL: ${VITE_API_URL}
    container_name: jewellery-catalogue-web 
    env_file:
    - .env
    ports:
      - '3000:80'
    depends_on:
      - jewellery-catalogue-api

volumes:
  jewellery-catalogue-mongo-data:
  jewellery-catalogue-minio-data:
